Packy and i3theme updates
Packy gets a small update, it handles better makepkg errors. Now it detects if makepkg exits with no errors and if the package is already built, useful if sudo password expires.
i3theme now better detects the theme dependencies. It checks if the package is installed, and if not, check if its a theme and if its installed on /usr/share/themes.

diff --git a/i3theme/i3theme b/i3theme/i3theme
--- a/i3theme/i3theme
+++ b/i3theme/i3theme
@@ -127,6 +127,15 @@ function verifyJSON() {
   fi
 }
 
+# check if theme is present on /usr/share/theme
+function themeExists() {
+  if [[ -e "/usr/share/themes/$1" ]]; then
+    return 0
+  else
+    return 1
+  fi
+}
+
 # list all the themes avaiable
 if [ "$listThemesF" ]; then
   echo "${GREEN}::${RESTORE}${BOLD} Themes avaiable: ${RESTORE}"
@@ -167,11 +176,17 @@ if [ "$changeGTKThemeF" ]; then
   # check if dependencies are met
   themeDependencies=$( echo $themeJSON | jq -r '.["dependencies"][]' )
   for pkg in ${themeDependencies[@]}; do
-    checkDependency=$(pacman -Q $pkg)
+    checkDependency=$(pacman -Q $pkg )
     exitStatus=$?
     if [ "$exitStatus" -eq 1 ]; then
-      echo ${RED}::${RESTORE}${BOLD} Missing dependencies: Please install $pkg ${RESTORE}
-      exit 2
+      # check if theme is installed, but its not a package
+      echo "${YELLOW}::${RESTORE}${BOLD} Package '$pkg' not found, maybe its a theme name? Checking... ${RESTORE}"
+      if themeExists "$pkg"; then
+        echo "${GREEN}::${RESTORE}${BOLD} Theme found, continuing... ${RESTORE}"
+      else
+        echo "${RED}::${RESTORE}${BOLD} Error: Please install '$pkg' or if it's a GTK theme, copy it to /usr/share/themes ${RESTORE}"
+        exit 2
+      fi
     fi
   done
 
diff --git a/packy/packy b/packy/packy
--- a/packy/packy
+++ b/packy/packy
@@ -431,18 +431,24 @@ if [ "$downloadPkg" ]; then
         # need some work here, to get the makepkg error but still output its progress
         # makepkg with -s (build package) and -c (clean after sucessful build)
         makepkg -sc
-        #makePkg=$(makepkg -s)
-        #makePkgExitStatus=$?
-        #if [ "$curlURLExitStatus" -eq 0 ]; then
+        makePkgExitStatus=$?
+        # check if package is already built
+        if [ "$makePkgExitStatus" -eq 13 ]; then
+          whileString="${YELLOW}::${RESTORE} ${BOLD} Package '$pkgString' is already built. Continue? [yes] [no] : ${RESTORE}"
+          printf "$whileString"
+          while read key; do
+            case "$key" in
+              # if yes then continues the installation
+              y|yes) continueInstall=1; break ;;
+              n|no) echo "${BOLD}:: Exiting... ${RESTORE}" ; exit 2 ;;
+              *) printf "${RED}::${RESTORE} Error: Unknown option '$key'.${RESTORE}\n" ; printf "$whileString" ;;
+            esac
+          done
+        fi
+        # check is makepkg compile sucessfully
+        if [[ "$makePkgExitStatus" -eq 0 || "$continueInstall" ]]; then
           compilePkg=$(ls $pkgLocation/*.pkg.tar.zst)
-          echo
           echo ::${BOLD} makepkg complete.${RESTORE}
-          echo ${GREEN}::${RESTORE}${BOLD} If successful, use [ pacman -U $compilePkg ] to install $pkgString${RESTORE}
-          echo ${RED}::${RESTORE}${BOLD} If not, check for errors above ${RESTORE}
-          #exit 0
-        #else
-          #echo ${BOLD}:: makepkg complete but with errors! ${RESTORE}
-          #echo ${BOLD}:: Check for errors above ${RESTORE}
           if [[ -e "$compilePkg" ]]; then
             whileString="${BOLD}:: Install $pkgString? [yes] [no] : ${RESTORE}"
             printf "$whileString"
@@ -455,7 +461,12 @@ if [ "$downloadPkg" ]; then
             done
           fi
           exit 0
-        #fi
+        else
+          echo
+          echo ${RED}::${RESTORE}${BOLD} makepkg complete but with errors! ${RESTORE}
+          echo ${RED}::${RESTORE}${BOLD} Check for makepkg errors above ${RESTORE}
+          exit 2
+        fi
       fi
       exit 0
     else
